	[colors]
	[colors.primary]
	foreground = "#504944"
	background = "#f1eded"
	dim_foreground = "#443e39"
	bright_foreground = "#5d554f"
	[colors.cursor]
	text = "#504944"
	cursor = "#d1882f"
	[colors.vi_mode_cursor]
	text = "#504944"
	cursor = "#bf7c2a"
	[colors.search]
	[colors.search.matches]
	foreground = "#522F86"
	background = "#d7d6f1"
	[colors.search.focused_match]
	foreground = "#4a2a7a"
	background = "#a89edf"
	[colors.hints]
	[colors.hints.start]
	foreground = "#bcbee8"
	background = "#1E5571"
	[colors.hints.end]
	foreground = "#1E5571"
	background = "#bcbee8"
	[colors.line_indicator]
	foreground = "#423333"
	background = "#d2c3c3"
	[colors.footer_bar]
	foreground = "#423333"
	background = "#d2c3c3"
	[colors.selection]
	text = "#522F86"
	background = "#d7d6f1"
	[colors.normal]
	black = "#504944"
	red = "#d30505"
	green = "#5e8a36"
	yellow = "#bba53b"
	blue = "#296e92"
	magenta = "#60389b"
	cyan = "#377166"
	white = "#bfb8b3"
	[colors.bright]
	black = "#69605a"
	red = "#d30505"
	green = "#72a643"
	yellow = "#d9c046"
	blue = "#296e92"
	magenta = "#6e41b1"
	cyan = "#377166"
	white = "#e4dbdb"
	[colors.dim]
	black = "#38332f"
	red = "#a50303"
	green = "#4b6f2a"
	yellow = "#9d8b30"
	blue = "#1e5571"
	magenta = "#452771"
	cyan = "#29574e"
	white = "#a39d99"

