[colors]
[colors.primary]
foreground = "#aaaab5"
background = "#1F1F29"
dim_foreground = "#5f5f72"
[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"
[colors.search]
[colors.search.matches]
foreground = "#c8c8d0"
background = "#2e2e3c"
[colors.search.focused_match]
foreground = "#2e2e3c"
background = "#c8c8d0"
[colors.hints]
[colors.hints.start]
foreground = "#69aafd"
background = "#292a3d"
[colors.hints.end]
foreground = "#aaaab5"
background = "#1F1F29"
[colors.line_indicator]
foreground = "#2e2e3c"
background = "#c8c8d0"
[colors.footer_bar]
foreground = "#9fa4a4"
background = "#151717"
[colors.selection]
text = "#c8c8d0"
background = "#2e2e3c"
[colors.normal]
black = "#bbbbbb"
red = "#F55661"
green = "#70cf92"
yellow = "#cfb787"
blue = "#69aafd"
magenta = "#b5a0ff"
cyan = "#18c6ce"
white = "#f5f5f5"
[colors.bright]
black = "#bbbbbb"
red = "#F55661"
green = "#70cf92"
yellow = "#cfb787"
blue = "#69aafd"
magenta = "#b5a0ff"
cyan = "#18c6ce"
white = "#f5f5f5"

