[colors]
[colors.primary]
foreground = "#DCDBDB"
background = "#23212C"
dim_foreground = "#81747d"
[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"
[colors.search]
[colors.search.matches]
foreground = "#DCDBDB"
background = "#474356"
[colors.search.focused_match]
foreground = "#2e2b42"
background = "#69aafd"
[colors.hints]
[colors.hints.start]
foreground = "#69aafd"
background = "#2e2b42"
[colors.hints.end]
foreground = "#DCDBDB"
background = "#23212C"
[colors.line_indicator]
foreground = "#2e2b42"
background = "#69aafd"
[colors.footer_bar]
foreground = "#DCDBDB"
background = "#474356"
[colors.selection]
text = "#DCDBDB"
background = "#474356"
[colors.normal]
black = "#DCDBDB"
red = "#F55661"
green = "#70cf92"
yellow = "#cfb787"
blue = "#69aafd"
magenta = "#b5a0ff"
cyan = "#18c6ce"
white = "#f5f5f5"
[colors.bright]
black = "#DCDBDB"
red = "#F55661"
green = "#70cf92"
yellow = "#cfb787"
blue = "#69aafd"
magenta = "#b5a0ff"
cyan = "#18c6ce"
white = "#f5f5f5"

