[colors]
[colors.primary]
foreground = "#DCDBDB"
background = "#211F29"
dim_foreground = "#6c616b"
[colors.cursor]
text = "#33313f"
cursor = "#DCDBDB"
[colors.vi_mode_cursor]
text = "#33313f"
cursor = "#DCDBDB"
[colors.search]
[colors.search.matches]
foreground = "#DCDBDB"
background = "#454253"
[colors.search.focused_match]
foreground = "#2d293f"
background = "#69aafd"
[colors.hints]
[colors.hints.start]
foreground = "#69aafd"
background = "#2d293f"
[colors.hints.end]
foreground = "#DCDBDB"
background = "#211F29"
[colors.line_indicator]
foreground = "#2d293f"
background = "#69aafd"
[colors.footer_bar]
foreground = "#DCDBDB"
background = "#33313f"
[colors.selection]
text = "#DCDBDB"
background = "#454253"
[colors.normal]
black = "#DCDBDB"
red = "#F55661"
green = "#70cf92"
yellow = "#cfb787"
blue = "#69aafd"
magenta = "#b5a0ff"
cyan = "#18c6ce"
white = "#f5f5f5"
[colors.bright]
black = "#DCDBDB"
red = "#F55661"
green = "#70cf92"
yellow = "#cfb787"
blue = "#69aafd"
magenta = "#b5a0ff"
cyan = "#18c6ce"
white = "#f5f5f5"

