[colors]
[colors.primary]
foreground = "#3D3C44"
background = "#F1EDED"
dim_foreground = "#b19da8"
[colors.cursor]
text = "#e6dfdf"
cursor = "#3D3C44"
[colors.vi_mode_cursor]
text = "#e6dfdf"
cursor = "#3D3C44"
[colors.search]
[colors.search.matches]
foreground = "#3D3C44"
background = "#dcd2d2"
[colors.search.focused_match]
foreground = "#e5dcf3"
background = "#3856d1"
[colors.hints]
[colors.hints.start]
foreground = "#3856d1"
background = "#e5dcf3"
[colors.hints.end]
foreground = "#3D3C44"
background = "#F1EDED"
[colors.line_indicator]
foreground = "#e5dcf3"
background = "#3856d1"
[colors.footer_bar]
foreground = "#3D3C44"
background = "#e6dfdf"
[colors.selection]
text = "#3D3C44"
background = "#dcd2d2"
[colors.normal]
black = "#3D3C44"
red = "#B22E32"
green = "#346e27"
yellow = "#b17900"
blue = "#3856d1"
magenta = "#8f35bd"
cyan = "#2c6a73"
white = "#909098"
[colors.bright]
black = "#3D3C44"
red = "#B22E32"
green = "#346e27"
yellow = "#b17900"
blue = "#3856d1"
magenta = "#8f35bd"
cyan = "#2c6a73"
white = "#909098"

