[colors]
[colors.primary]
foreground = "#3D3C44"
background = "#F1EDED"
dim_foreground = "#9f8a99"
[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"
[colors.search]
[colors.search.matches]
foreground = "#5c4040"
background = "#e5dede"
[colors.search.focused_match]
foreground = "#e5dede"
background = "#5c4040"
[colors.hints]
[colors.hints.start]
foreground = "#42267d"
background = "#ccc2f2"
[colors.hints.end]
foreground = "#3D3C44"
background = "#F1EDED"
[colors.line_indicator]
foreground = "#e5dede"
background = "#5c4040"
[colors.footer_bar]
foreground = "#5c4040"
background = "#e6dfdf"
[colors.selection]
text = "#5c4040"
background = "#e5dede"
[colors.normal]
black = "#3D3C44"
red = "#B22E32"
green = "#346e27"
yellow = "#b17900"
blue = "#3856d1"
magenta = "#8f35bd"
cyan = "#2c6a73"
white = "#909098"
[colors.bright]
black = "#3D3C44"
red = "#B22E32"
green = "#346e27"
yellow = "#b17900"
blue = "#3856d1"
magenta = "#8f35bd"
cyan = "#2c6a73"
white = "#909098"

