[colors]
[colors.primary]
foreground = "#d6d5d5"
background = "#353341"
dim_foreground = "#7d7979"
[colors.cursor]
text = "#353341"
cursor = "#d6d5d5"
[colors.vi_mode_cursor]
text = "#353341"
cursor = "#d6d5d5"
[colors.search]
[colors.search.matches]
foreground = "#eae9e9"
background = "#474355"
[colors.search.focused_match]
foreground = "#3d3b51"
background = "#69aafd"
[colors.hints]
[colors.hints.start]
foreground = "#69aafd"
background = "#3d3b51"
[colors.hints.end]
foreground = "#d6d5d5"
background = "#353341"
[colors.line_indicator]
foreground = "#3d3b51"
background = "#69aafd"
[colors.footer_bar]
foreground = "#e0dfdf"
background = "#3e3b4b"
[colors.selection]
text = "#eae9e9"
background = "#474355"
[colors.normal]
black = "#d6d5d5"
red = "#F55661"
green = "#70cf92"
yellow = "#cfb787"
blue = "#69aafd"
magenta = "#b5a0ff"
cyan = "#18c6ce"
white = "#f5f5f5"
[colors.bright]
black = "#d6d5d5"
red = "#F55661"
green = "#70cf92"
yellow = "#cfb787"
blue = "#69aafd"
magenta = "#b5a0ff"
cyan = "#18c6ce"
white = "#f5f5f5"

