[colors]
[colors.primary]
foreground = "#B0ABAB"
background = "#1F2029"
dim_foreground = "#6a5f67"
[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"
[colors.search]
[colors.search.matches]
foreground = "#171820"
background = "#9295a6"
[colors.search.focused_match]
foreground = "#292b3c"
background = "#69aafd"
[colors.hints]
[colors.hints.start]
foreground = "#69aafd"
background = "#292b3c"
[colors.hints.end]
foreground = "#B0ABAB"
background = "#1F2029"
[colors.line_indicator]
foreground = "#292b3c"
background = "#69aafd"
[colors.footer_bar]
foreground = "#9295a6"
background = "#171820"
[colors.selection]
text = "#171820"
background = "#9295a6"
[colors.normal]
black = "#B0ABAB"
red = "#F55661"
green = "#70cf92"
yellow = "#cfb787"
blue = "#69aafd"
magenta = "#b5a0ff"
cyan = "#18c6ce"
white = "#f5f5f5"
[colors.bright]
black = "#B0ABAB"
red = "#F55661"
green = "#70cf92"
yellow = "#cfb787"
blue = "#69aafd"
magenta = "#b5a0ff"
cyan = "#18c6ce"
white = "#f5f5f5"

